collections:
  projects:
    output: true
plugins:
  - jekyll-feed
theme: roz-aer
title: Joëlle Richol, candidate Nouveau Front Populaire
description: Le site de la candidate du Nouveau Front Populaire aux élections législatives dans la 10ème circonscription de l'Isère
